# -*- coding: utf-8 -*-
"""Numpy-Dersleri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8Z1AV_J82hdj_hoXOZcsYxUAfURTaNM

#Matrislerde Matematiksel İşlemler
"""

import numpy as np


m1=np.ones((5,5))

m2=np.full((5,5),19)

m1

m2

m1=m1.astype("int16")

m1

m1*4

m2+3

m2+m1

m2/3

m2//3

m2%2

m3=np.full((5,6),2)

m3

m2

m2.shape

m3.shape

m3.reshape(30)[:25].reshape(5,5)+m2

m1

m1[0]=m1[0]*3

m1

m1

m5=np.arange(5).reshape((5,1))

m5

m5*m1

m1/m5

m6=m1+m5

m6

m6*np.diag(m6)