# -*- coding: utf-8 -*-
"""Numpy-Dersleri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8Z1AV_J82hdj_hoXOZcsYxUAfURTaNM

#Matrislerde Slice
"""

import numpy as np

matris=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(matris)

matris[0]

matris[1]

matris[1:3]

matris[0,:]

matris[0,:2] #virgüün sol tarafı satırlar sağ tarafı sütünlar.

matris[0:4,0:1]

matris[0:4,1:3]

matris[1:3,1:3]

"""#Random Matris Oluşturma

"""

dir(np.random)

np.random.randint(0,5)

np.random.randint(0,5,(4,4))

np.random.randint(0,10,(4,4))/10