# -*- coding: utf-8 -*-
"""Numpy-Dersleri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8Z1AV_J82hdj_hoXOZcsYxUAfURTaNM

#Numpy Yeniden Boyutlandırma reshape() Methodu
"""

import numpy as np

m1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(m1)

m1.shape

m1.size

m1.reshape(4,3)

m1.reshape(2,6)

m1.reshape(12,1)

np.random.randint(0,2,(8,6)).reshape(4,12)

np.linspace(0,20,30).reshape(6,5)

"""#copy()  & view() Methotları"""

matris=np.random.randint(0,5,(4,4))
print(matris)

matris2=matris.view()
print(matris2)

matris2[0]

matris2[0]=[9,9,9,9]
print(matris2)

matris

matris3=np.random.randint(0,5,(4,4))
print(matris3)

matris4=matris3.copy()
print(matris4)

matris4[0]=[9,9,9,9]
print(matris4)

matris3

"""copy'de bir değişiklik yaptığımda ilk oluşturduğum yapı değişmezz ama view'de bütün yapıları etkiler."""