# -*- coding: utf-8 -*-
"""Numpy-Dersleri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8Z1AV_J82hdj_hoXOZcsYxUAfURTaNM

#Size,Shape,Dtype,ndim
"""

import numpy as np

vektor =np.array([1,2,3,4,5,6])
matris =np.array([[1,2,3],[4,5,6],[7,8,9]])

print(vektor)

print(matris)

vektor.size #size Boyutnu verir.

matris.size

vektor.shape #shape Şeklini verir.

matris.shape

vektor.ndim  #ndim kaç boyutlu olduğunu gösterir.

matris.ndim

vektor.dtype #dtype veri türünü verir

matris.dtype