# -*- coding: utf-8 -*-
"""Numpy-Dersleri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8Z1AV_J82hdj_hoXOZcsYxUAfURTaNM

#Numpy Veir Tipi Değiştirme
"""

import numpy as np

sayilar=np.array([1,2,3,4,5,6])

sayilar.dtype

sayilar=np.array([1,2,3,4,5.0,6])

sayilar.dtype

sayilar=np.array([1,2,3,4,5.0,6,"kadir"])

sayilar.dtype

sayilar=np.array([1,2,3,4,5.0,6])

sayilar=sayilar.astype("int64")

sayilar.dtype

sayilar=np.array([1,2,3,4,5.0,6],dtype="int8")
sayilar.dtype #baştanda belirtilebilir.

tarih=np.array(["2025-05-18"])
tarih.dtype

tarih=tarih.astype("datetime64[ns]")
tarih.dtype