# -*- coding: utf-8 -*-
"""Numpy-Dersleri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8Z1AV_J82hdj_hoXOZcsYxUAfURTaNM

#Numpy ile Mantıksal operatörler ve Filtreleme
"""

import numpy as np

matris=np.random.randint(0,10,(5,5))

matris

matris>5

matris[matris>5]

matris[matris<5]

matris[matris>=5]

matris[matris==5]

matris[matris==7].size

matris[matris!=7].size

matris%2 == 0

matris[matris%2==0]

sifir=matris != 0 #sıfıra eşit olmayıp çift olan değerleri getir.
cift=matris%2==0

matris[cift & sifir]

bir=matris==1

matris[cift | bir]

matris[(cift & sifir)| bir]

matris.shape

m2=np.full((5,5),5)

m2

m2[(cift & sifir)| bir]