# -*- coding: utf-8 -*-
"""Numpy-Dersleri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8Z1AV_J82hdj_hoXOZcsYxUAfURTaNM

Neden Numpy?

#Python
"""

import time

z1=time.time()
liste = []
for a in range(1_000_000):
  kuvvet = a**100
  liste.append(kuvvet)

z2=time.time()
print(z2-z1)

"""#Numpy"""

import numpy as np

z3=time.time()
liste2=np.arange(1_000_000)**100
z4=time.time()
print(z4-z3)

"""#numpy pythona göre 100 kat daha hızlıdır.

#index & Slice
"""

vektor = np.array([0,2,4,5,6,7,8,15])

vektor[3]

vektor[0]

vektor[-1]

vektor[1:3]

vektor[:5]

vektor[2:6:2] #başlangıç:bitiş:artış miktarı