# -*- coding: utf-8 -*-
"""Numpy-Dersleri

Automatically generated by Colab.



import numpy as np

np.array([1,2,3])

skaler=np.array(90)
print(skaler)

vektor=np.array([1,2,3,4,5,6])
print(vektor)

matris = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matris)

tensor=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tensor)