# -*- coding: utf-8 -*-
"""Numpy-Dersleri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8Z1AV_J82hdj_hoXOZcsYxUAfURTaNM

#Atrange ile Vektör oluşturma
"""

import numpy as np

liste=[1,2,3,4,5,6]
range(1000000)

milyon=np.arange(1000000)
print(milyon)

np.arange(10)

np.arange(5,10)

np.arange(1,20,2) #1 başalngıç 20 bitiş 2 artış miktarı.

"""#linespace() ile vektör oluşturma"""

np.linspace(1,10,6) #1 başlangıç 10 bitiş 6 kaç eşit parçacığa bölüneceği

bol=np.linspace(5,25,15)
print(bol)

bol[1]-bol[0] #aralarındaki farkın eşit olduğunun kanıtı.

bol[5]-bol[4]